/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Models.Account;
import Models.Transaction;
import Models.TransactionType;
import Models.User;
import javax.swing.JOptionPane;


/**
 *
 * @author fgarr
 */
public class GenericShowWindow extends javax.swing.JPanel {
    
    private ATM actualFrame;
    private Generic7Window generic7Window;
    private Generic4Window generic4Window;
    private User user;
    private Account account;
    private Account account2;
    private Transaction transaction;
    private MainMenuWindow mainMenuWindow;
    private TransactionType transactionType;
    private int id;

    /**
     * Creates new form GenericShowWindow
     */
    public GenericShowWindow(ATM actualFrame, Generic7Window generic7Window, User user, Account account, Account account2, Transaction transaction, MainMenuWindow mainMenuWindow, TransactionType transactionType) {
        this.actualFrame = actualFrame;
        this.generic7Window = generic7Window;
        this.user = user;
        this.account = this.actualFrame.aService.getAccountById(account.getId());
        this.account2 = account2;
        this.transaction = transaction;
        this.mainMenuWindow = mainMenuWindow;
        this.transactionType = transactionType;
        id = 0;
        initComponents();
        fillTxt();
    }
    
    public GenericShowWindow(ATM actualFrame, Generic4Window generic7Window, User user, Account account, Account account2, Transaction transaction, MainMenuWindow mainMenuWindow, TransactionType transactionType) {
        this.actualFrame = actualFrame;
        this.generic4Window = generic4Window;
        this.user = user;
        this.account = this.actualFrame.aService.getAccountById(account.getId());
        this.account2 = account2;
        this.transaction = transaction;
        this.mainMenuWindow = mainMenuWindow;
        this.transactionType = transactionType;
        id = 0;
        initComponents();
        fillTxt();
    }
    
    public GenericShowWindow(ATM actualFrame, Generic4Window generic4Window, User user, MainMenuWindow mainMenuWindow, int id){
        this.actualFrame = actualFrame;
        this.generic4Window = generic4Window;
        this.user = user;
        this.id = id;
        this.transaction = actualFrame.tservice.getTransactionById(id);
        this.account = actualFrame.aService.getAccountById(transaction.getOriginAccount());
        this.account2 = actualFrame.aService.getAccountById(transaction.getDestinyAccount());
        this.mainMenuWindow = mainMenuWindow;
        initComponents();
        fillTxt();
    }

    private void fillTxt() {
        lblInstructions2.setText(" # " + transaction.getId());
        if (account.getClientId() == Integer.parseInt(user.getId())){           
            lblInfo1.setText("Transaction type: " + transaction.getType());
            lblInfo2.setText("User: " + user.getName());
            lblInfo3.setText("Origin account name: " + account.getName());
            lblInfo4.setText("Destiny account name: " + account2.getName());
            lblInfo5.setText("Ammount of the transaction: $" + transaction.getAmount());
            lblInfo6.setText("Current origin acount balance: $" + account.getBalance());
            if (id != 0) {
                lblInfo6.setText("");
            }
        } else {
            lblInfo1.setText("The transaction");
            lblInfo2.setText("");
            lblInfo3.setText("does not belong" );
            lblInfo4.setText("");
            lblInfo5.setText("to the selected user!!!");
            lblInfo6.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMainMenu = new javax.swing.JButton();
        btnAction = new javax.swing.JButton();
        lblInstructions1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblInfo6 = new javax.swing.JLabel();
        lblInfo1 = new javax.swing.JLabel();
        lblInfo2 = new javax.swing.JLabel();
        lblInfo3 = new javax.swing.JLabel();
        lblInfo4 = new javax.swing.JLabel();
        lblInfo5 = new javax.swing.JLabel();
        imgSecondaryLogo = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 5, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMainMenu.setBackground(new java.awt.Color(24, 58, 90));
        btnMainMenu.setFont(new java.awt.Font("Franklin Gothic Book", 0, 28)); // NOI18N
        btnMainMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMainMenu.setText("Main menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        add(btnMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 830, 200, 70));

        btnAction.setBackground(new java.awt.Color(24, 58, 90));
        btnAction.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        btnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnAction.setText("Print");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        add(btnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, 460, 70));

        lblInstructions1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions1.setText("Transaction summary!");
        lblInstructions1.setToolTipText("");
        add(lblInstructions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo6.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblInfo6.setForeground(new java.awt.Color(102, 102, 102));
        lblInfo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo6.setText("jLabel1");
        jPanel1.add(lblInfo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 590, 30));

        lblInfo1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblInfo1.setForeground(new java.awt.Color(102, 102, 102));
        lblInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo1.setText("jLabel1");
        jPanel1.add(lblInfo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 590, 30));

        lblInfo2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblInfo2.setForeground(new java.awt.Color(102, 102, 102));
        lblInfo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo2.setText("jLabel1");
        jPanel1.add(lblInfo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 590, 30));

        lblInfo3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblInfo3.setForeground(new java.awt.Color(102, 102, 102));
        lblInfo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo3.setText("jLabel1");
        jPanel1.add(lblInfo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 590, 30));

        lblInfo4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblInfo4.setForeground(new java.awt.Color(102, 102, 102));
        lblInfo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo4.setText("jLabel1");
        jPanel1.add(lblInfo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 590, 30));

        lblInfo5.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        lblInfo5.setForeground(new java.awt.Color(102, 102, 102));
        lblInfo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfo5.setText("jLabel1");
        jPanel1.add(lblInfo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 590, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 600, 433));

        imgSecondaryLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SecondaryLogo.png"))); // NOI18N
        imgSecondaryLogo.setText("jLabel1");
        add(imgSecondaryLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 110));

        lblInstructions2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions2.setText("Transaction summary!");
        lblInstructions2.setToolTipText("");
        add(lblInstructions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 700, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        actualFrame.showPanel(mainMenuWindow);// TODO add your handling code here:
    }//GEN-LAST:event_btnMainMenuActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        System.out.println("\n\n\nTransaction summary:");
        System.out.println("\n\n" + lblInfo1.getText());
        System.out.println("\n" + lblInfo2.getText());
        System.out.println("\n" + lblInfo3.getText());
        System.out.println("\n" + lblInfo4.getText());
        System.out.println("\n" + lblInfo5.getText());
        System.out.println("\n" + lblInfo6.getText());
        System.out.println("\n\n\n");
    }//GEN-LAST:event_btnActionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JLabel imgSecondaryLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfo1;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblInfo3;
    private javax.swing.JLabel lblInfo4;
    private javax.swing.JLabel lblInfo5;
    private javax.swing.JLabel lblInfo6;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    // End of variables declaration//GEN-END:variables
}
