/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Models.Account;
import Models.IdType;
import Models.Transaction;
import Models.TransactionType;
import Models.User;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fgarr
 */
public class Generic4Window extends javax.swing.JPanel {

    private ATM actualContainer;
    private String type;
    private User user;
    private MainMenuWindow mainMenuWindow;
    private LoginWindow loginWindow;
    private GenericShowWindow printDocuments;
    private Generic7Window generic7Window;
    private Account account1;
    private Account account2;
    private Transaction transaction;
    private TransactionType transactionType;
    private Float numberInput;
    
    /**
     * Creates new form Generic4Window
     */
    public Generic4Window(ATM actualContainer, String type, LoginWindow loginWindow, User user) {
        this.actualContainer = actualContainer;
        this.type = type;
        this.user = user;
        this.loginWindow = loginWindow;
        initComponents();
        fillText();
    }
    
    public Generic4Window(ATM actualConainer, Generic7Window generic7Window, User user, TransactionType transactionType, Account account1, Account account2, MainMenuWindow mainMenuWindow, Float numberInput, String type){
        this.actualContainer = actualConainer;
        this.generic7Window = generic7Window;
        this.user = user;
        this.transactionType = transactionType;
        this.account1 = account1;
        this.account2 = account2;
        this.mainMenuWindow = mainMenuWindow;
        this.numberInput = numberInput;
        this.type = type;
        initComponents();
        fillText();
    }
    
    public Generic4Window(ATM actualContainer, String type, User user, LoginWindow loginWindow, MainMenuWindow mainMenuWindow) {
        this.actualContainer = actualContainer;
        this.type = type;
        this.user = user;
        this.loginWindow = loginWindow;
        this.mainMenuWindow = mainMenuWindow;
        initComponents();
        fillText();
    }
    
    public Generic4Window(ATM actualContainer, String type, User user, MainMenuWindow mainMenuWindow) {
        this.actualContainer = actualContainer;
        this.type = type;
        this.user = user;
        this.mainMenuWindow = mainMenuWindow;
        initComponents();
        fillText();
    }
    
    
    
    
    private void fillText(){
        if (type.equals("NewUser") || type.equals("NewAccount")){
            lblInstructions1.setText("Please enter the name or purpose");
            lblInstructions2.setText("for the new account:");
            txtInput.setText("Account name");
            btnAction.setText("Create new account");
        } else if (type.equals("PrintDocuments")){
            lblInstructions1.setText("Enter the number of the");
            lblInstructions2.setText("transaction to print:");
            txtInput.setText("Transaction number");
            btnAction.setText("Search");
        } else if (type.equals("Transfer")){
            lblInstructions1.setText("Enter the number of the");
            lblInstructions2.setText("destiny account:");
            txtInput.setText("Destiny account");
            btnAction.setText("Transfer now!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInput = new javax.swing.JTextField();
        btnAction = new javax.swing.JButton();
        lblInstructions1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblInstructions2 = new javax.swing.JLabel();
        imgSecondaryLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 5, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInput.setBackground(new java.awt.Color(134, 138, 146));
        txtInput.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        txtInput.setForeground(new java.awt.Color(255, 255, 255));
        txtInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInput.setText("TXT");
        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 460, 70));

        btnAction.setBackground(new java.awt.Color(24, 58, 90));
        btnAction.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        btnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnAction.setText("TXT");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        add(btnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 460, 70));

        lblInstructions1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions1.setText("TXT");
        add(lblInstructions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 700, 60));

        btnBack.setBackground(new java.awt.Color(24, 58, 90));
        btnBack.setFont(new java.awt.Font("Franklin Gothic Book", 0, 28)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 830, 200, 70));

        lblInstructions2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        lblInstructions2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions2.setText("TXT");
        add(lblInstructions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 700, 60));

        imgSecondaryLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SecondaryLogo.png"))); // NOI18N
        imgSecondaryLogo.setText("jLabel1");
        add(imgSecondaryLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        if (type.equals("NewAccount")) {
            if (txtInput.getText().equals("Account name")) {
                JOptionPane.showMessageDialog(null, "Please change the account name.");
            } else {
                actualContainer.aService.addAccount(txtInput.getText(), Long.parseLong(user.getId()));
                txtInput.setText("Account name");
                JOptionPane.showMessageDialog(null, "Account created succesfully");
                mainMenuWindow = new MainMenuWindow(actualContainer, loginWindow, user);
                actualContainer.showPanel(mainMenuWindow);
            }
        } else if (type.equals("PrintDocuments")) {
            int transactionNumber = 0;
            try {
                transactionNumber = Integer.parseInt(txtInput.getText());
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a numeric value");
                return;
            }
            printDocuments = new GenericShowWindow(actualContainer, this, user, mainMenuWindow, transactionNumber);
            actualContainer.showPanel(printDocuments);
        } else if (type.equals("NewUser")) {
            if (txtInput.getText().equals("Account name")) {
                JOptionPane.showMessageDialog(null, "Please change the account name.");
            } else {
                actualContainer.aService.addAccount(txtInput.getText(), Long.parseLong(user.getId()));
                txtInput.setText("Account name");
                JOptionPane.showMessageDialog(null, "Account created succesfully");
                mainMenuWindow = new MainMenuWindow(actualContainer, loginWindow, user);
                actualContainer.showPanel(mainMenuWindow);
            }
        } else if (type.equals("Transfer")){
            int transactionNumber = 0;
            try {
                transactionNumber = Integer.parseInt(txtInput.getText());
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a numeric value");
                return;
            }
         
            account2 = actualContainer.aService.getAccountById(transactionNumber);
            actualContainer.tservice.addTransaction(TransactionType.TRANSFER, "Transfer", account1.getId(), account2.getId(), numberInput);
            try {
                transaction = actualContainer.tservice.getTransactionById(actualContainer.idService.getLastId(IdType.TRANSACTIONID));
            } catch (IOException ex) {
                System.out.println("Error");
            }
            printDocuments = new GenericShowWindow(actualContainer, this, user, account1, account2, transaction, mainMenuWindow, transactionType);
            actualContainer.showPanel(printDocuments);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnActionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (type.equals("NewUser")){
            actualContainer.showPanel(loginWindow); 
        } else if (type.equals("NewAccount")){
            actualContainer.showPanel(mainMenuWindow); 
        } else if (type.equals("PrintDocuments")){
            actualContainer.showPanel(mainMenuWindow); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel imgSecondaryLogo;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
