/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Models.User;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fgarr
 */
public class LoginWindow extends javax.swing.JPanel {

    MainLogo logo = new MainLogo();
    private MainMenuWindow mainMenuWindow;
    private NewUserWindow newUserWindow;
    private final ATM actualContainer;
    private Generic4Window newAccountWindow;

    /**
     * Creates new form LoginWindow
     *
     * @param container
     */
    public LoginWindow(ATM container) {
        initComponents();
        this.actualContainer = container;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddService = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblimage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 255), 5, true));
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddService.setBackground(new java.awt.Color(134, 138, 146));
        btnAddService.setFont(new java.awt.Font("Franklin Gothic Book", 0, 66)); // NOI18N
        btnAddService.setForeground(new java.awt.Color(255, 255, 255));
        btnAddService.setText("+");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });
        add(btnAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 790, 70, 70));

        txtUser.setBackground(new java.awt.Color(134, 138, 146));
        txtUser.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setText("User");
        txtUser.setToolTipText("User");
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 460, 70));

        btnLogin.setBackground(new java.awt.Color(24, 58, 90));
        btnLogin.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 700, 460, 70));

        lblLogo.setFont(new java.awt.Font("Franklin Gothic Book", 1, 36)); // NOI18N
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("Your trusted bank!");
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 700, 60));

        txtPassword.setBackground(new java.awt.Color(134, 138, 146));
        txtPassword.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("Password");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 460, 70));

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MainLogo.png"))); // NOI18N
        add(lblimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (actualContainer.uService.login(txtUser.getText(), txtPassword.getText())) {
            User user = actualContainer.uRepo.getUserByUser(txtUser.getText());
            System.out.println("user = " + user);
            System.out.println(actualContainer.aService.getAccountsByClientId(Long.parseLong(user.getId())));
            if (actualContainer.aService.getAccountsByClientId(Long.parseLong(user.getId())).isEmpty()) {
                newAccountWindow = new Generic4Window(actualContainer, "NewUser", this, user);
                actualContainer.showPanel(newAccountWindow);
            } else {
                mainMenuWindow = new MainMenuWindow(actualContainer, this, user);
                actualContainer.showPanel(mainMenuWindow);
            }
            clearTxt();
        } else {
            txtUser.setText("User");
            txtPassword.setText("Password");
            JOptionPane.showMessageDialog(null, "Invalid credentials. Please try again.");
            clearTxt();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    public void clearTxt(){
        txtUser.setText("User");
        txtPassword.setText("Password");
    }
    
    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        newUserWindow = new NewUserWindow(actualContainer, this);
        actualContainer.showPanel(newUserWindow);
    }//GEN-LAST:event_btnAddServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblimage;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
class MainLogo extends JPanel {

        private final Image imagen;
        public MainLogo() {

            imagen = new ImageIcon(getClass().getResource("/images/MainLogo.png")).getImage();
        }

        @Override
        protected void paintComponent(Graphics g) {

            super.paintComponent(g);
            if (imagen != null) {
                gdrawImagen(imagen, 0, 0, getWidth(), getHeight(), this);
            }

        }

        private void gdrawImagen(Image imagen, int i, int i0, int width, int height, MainLogo aThis) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
