/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Models.IdType;
import Repositories.UserRepository;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fgarr
 */
public class NewUserWindow extends javax.swing.JPanel {
    
    private ATM actualContainer;
    private LoginWindow loginWindow;

    /**
     * Creates new form NewUserWindow
     */
    public NewUserWindow(ATM actualContainer, LoginWindow loginWindow) {
        this.actualContainer = actualContainer;
        this.loginWindow = loginWindow;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        txtNationalID = new javax.swing.JTextField();
        btnNewUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblInstructions3 = new javax.swing.JLabel();
        lblInstructions1 = new javax.swing.JLabel();
        lblInstructions2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblInstructions4 = new javax.swing.JLabel();
        imgSecondaryLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 5, true));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setBackground(new java.awt.Color(134, 138, 146));
        txtUser.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setText("User Name");
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 460, 70));

        txtNationalID.setBackground(new java.awt.Color(134, 138, 146));
        txtNationalID.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        txtNationalID.setForeground(new java.awt.Color(255, 255, 255));
        txtNationalID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNationalID.setText("ID");
        txtNationalID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalIDActionPerformed(evt);
            }
        });
        add(txtNationalID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 460, 70));

        btnNewUser.setBackground(new java.awt.Color(24, 58, 90));
        btnNewUser.setFont(new java.awt.Font("Franklin Gothic Book", 0, 36)); // NOI18N
        btnNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnNewUser.setText("Create new user");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });
        add(btnNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 460, 70));

        btnBack.setBackground(new java.awt.Color(24, 58, 90));
        btnBack.setFont(new java.awt.Font("Franklin Gothic Book", 0, 28)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, 210, 70));

        lblInstructions3.setFont(new java.awt.Font("Franklin Gothic Book", 0, 32)); // NOI18N
        lblInstructions3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions3.setText("start enjoying the benefits of our services");
        lblInstructions3.setToolTipText("");
        add(lblInstructions3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 700, -1));

        lblInstructions1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 32)); // NOI18N
        lblInstructions1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions1.setText("Welcome to Fidebank! We’re excited to have");
        lblInstructions1.setToolTipText("");
        add(lblInstructions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, -1));

        lblInstructions2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 32)); // NOI18N
        lblInstructions2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions2.setText("you join our family. Please provide the following");
        lblInstructions2.setToolTipText("");
        add(lblInstructions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 700, -1));

        txtPassword.setBackground(new java.awt.Color(134, 138, 146));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("Password");
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 460, 70));

        lblInstructions4.setFont(new java.awt.Font("Franklin Gothic Book", 0, 32)); // NOI18N
        lblInstructions4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstructions4.setText("information to create your new account and");
        lblInstructions4.setToolTipText("");
        add(lblInstructions4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 700, -1));

        imgSecondaryLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/SecondaryLogo.png"))); // NOI18N
        imgSecondaryLogo.setText("jLabel1");
        add(imgSecondaryLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtNationalIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalIDActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        if (txtNationalID.getText().isBlank() || txtUser.getText().isBlank() || txtUser.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
        } else {
            if (actualContainer.uRepo.getUserByUser(txtUser.getText()) == null){
                try {
                    actualContainer.uService.createUser(String.valueOf(actualContainer.idService.getLastId(IdType.USERID) + 1), txtUser.getText(), txtNationalID.getText(), txtPassword.getText());
                    actualContainer.idService.saveCounter(IdType.USERID, (actualContainer.idService.getLastId(IdType.USERID) + 1));
                    JOptionPane.showMessageDialog(null, "The user has been created successfully!");
                    actualContainer.showPanel(loginWindow);
                    clearTxt();
                } catch (IOException ex) {
                    Logger.getLogger(NewUserWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "The user already exists. Please try with another one.");
                clearTxt();
            }
        }
    }//GEN-LAST:event_btnNewUserActionPerformed

    public void clearTxt(){
        txtNationalID.setText("National ID");
        txtPassword.setText("Password");
        txtUser.setText("User Name");
    }
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        actualContainer.showPanel(loginWindow);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JLabel imgSecondaryLogo;
    private javax.swing.JLabel lblInstructions1;
    private javax.swing.JLabel lblInstructions2;
    private javax.swing.JLabel lblInstructions3;
    private javax.swing.JLabel lblInstructions4;
    private javax.swing.JTextField txtNationalID;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
